<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

function print_page_attachments(array &$page) {
  // $routeName = \Drupal::routeMatch()->getRouteName();
  // if (!in_array($routeName, [
  // 	'layout_builder.overrides.node.view', 
  // 	'layout_builder.defaults.node.view'
  // 	])) {
  //   $page['#attached']['library'] = array_diff($page['#attached']['library'], ['contextual/drupal.contextual-links', 'contextual/drupal.contextual-toolbar']);
  // }
}

function print_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  if (in_array($entity->getEntityTypeId(), ['taxonomy_term'])) {
 //   unset($build['#contextual_links']);
  }
}