print_settings.settings.*:
  type: config_object
  label: 'Print settings'
  mapping:
    marginT:
      type: number
      label: 'printer margin top'
    marginB:
      type: number
      label: 'printer margin bottom'
    marginW:
      type: number
      label: 'printer margin width' # on fait du recto verso => on prend la marge max gauche/droite pour les 2 cotés.
    versoOffsetY:
      type: number
      label: 'printer offset Y for verso'
    versoOffsetX:
      type: number
      label: 'printer offset X for verso'